import { Router } from 'express';
import { mealsController } from './meals.controller.js';
import { validate } from '../../common/middleware/validate.middleware.js';
import { CreateMealSchema, ListMealsSchema, UpdateMealSchema } from '../../common/schemas/request.schemas.js';
const router = Router();
export { router as mealsRouter };
router.post('/', validate(CreateMealSchema), mealsController.create);
router.get('/', validate(ListMealsSchema), mealsController.list);
router.get('/:id', mealsController.getOne);
router.patch('/:id', validate(UpdateMealSchema), mealsController.update);
router.delete('/:id', mealsController.remove);